# Generated by Django 3.1.5 on 2021-01-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timestamp',
            name='vacancies',
            field=models.ManyToManyField(related_name='vacancy', to='vacancies_api.Vacancy'),
        ),
    ]
